apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: k3w53cef7-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-1544ec7f2d.l69h.p3.openshiftapps.com/rhtap/rhtap-qe:ca76e5400cb8b8acd8c803a7ec6c9b6c183927e0@sha256:18cb5bd49cac2f7802e33e2616e8a06e2bcdf6ce42531c99d516ab6c48ffb132
          name: container-image
